on: [push, pull_request]
name: CI

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: ubuntu:production
            os: ubuntu-latest
            config: production --auto-download --all-bindings --editline --docs
            cache-key: production
            python-bindings: true
            build-documentation: true
            check-examples: true
            store-to-release: true
            exclude_regress: 3-4
            run_regression_args: --tester base --tester model --tester synth --tester abduct --tester dump

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    steps:

    - uses: actions/checkout@v2

    - name: Install dependencies
      uses: ./.github/actions/install-dependencies
      with:
        with-documentation: ${{ matrix.build-documentation }}
        with-python-bindings: ${{ matrix.python-bindings }}

    - name: Setup caches
      uses: ./.github/actions/setup-cache
      with:
        cache-key: ${{ matrix.cache-key }}

    - name: Configure and build
      id: configure-and-build
      uses: ./.github/actions/configure-and-build
      with:
        configure-env: ${{ matrix.env }}
        configure-config: ${{ matrix.config }}

    - name: ccache Statistics
      run: ccache -s

    - name: Build documentation
      if: matrix.build-documentation
      uses: ./.github/actions/build-documentation
      with:
        build-dir: ${{ steps.configure-and-build.outputs.shared-build-dir }}

    - name: Add binary to release
      if: matrix.store-to-release && startsWith(github.ref, 'refs/tags/')
      uses: ./.github/actions/add-to-release
      with:
        binary: ${{ steps.configure-and-build.outputs.static-build-dir }}/bin/cvc5
        github-token: ${{ secrets.GITHUB_TOKEN }}
